/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InnerComponent {
    }
    interface OuterComponent {
    }
}
declare global {
    interface HTMLInnerComponentElement extends Components.InnerComponent, HTMLStencilElement {
    }
    var HTMLInnerComponentElement: {
        prototype: HTMLInnerComponentElement;
        new (): HTMLInnerComponentElement;
    };
    interface HTMLOuterComponentElement extends Components.OuterComponent, HTMLStencilElement {
    }
    var HTMLOuterComponentElement: {
        prototype: HTMLOuterComponentElement;
        new (): HTMLOuterComponentElement;
    };
    interface HTMLElementTagNameMap {
        "inner-component": HTMLInnerComponentElement;
        "outer-component": HTMLOuterComponentElement;
    }
}
declare namespace LocalJSX {
    interface InnerComponent {
    }
    interface OuterComponent {
    }
    interface IntrinsicElements {
        "inner-component": InnerComponent;
        "outer-component": OuterComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inner-component": LocalJSX.InnerComponent & JSXBase.HTMLAttributes<HTMLInnerComponentElement>;
            "outer-component": LocalJSX.OuterComponent & JSXBase.HTMLAttributes<HTMLOuterComponentElement>;
        }
    }
}
